version: '2'

# Use this docker-compose file to setup the test environment before running the
# tests.
services:
  nsqlookupd-1:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - 4160:4160
      - 4161:4161

  nsqlookupd-2:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - 4162:4160
      - 4163:4161

  nsqlookupd-3:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - 4164:4160
      - 4165:4161

  nsqd-1:
    image: nsqio/nsq
    command: >
      /nsqd
      -lookupd-tcp-address nsqlookupd-1:4160
      -lookupd-tcp-address nsqlookupd-2:4160
      -lookupd-tcp-address nsqlookupd-3:4160
    ports:
      - 4150:4150
      - 4151:4151

  nsqd-2:
    image: nsqio/nsq
    command: >
      /nsqd
      -lookupd-tcp-address nsqlookupd-1:4160
      -lookupd-tcp-address nsqlookupd-2:4160
      -lookupd-tcp-address nsqlookupd-3:4160
    ports:
      - 4152:4150
      - 4153:4151

  nsqd-3:
    image: nsqio/nsq
    command: >
      /nsqd
      -lookupd-tcp-address nsqlookupd-1:4160
      -lookupd-tcp-address nsqlookupd-2:4160
      -lookupd-tcp-address nsqlookupd-3:4160
    ports:
      - 4154:4150
      - 4155:4151
